[project]
name = "dev-ops-course-hillel"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"

dependencies = [
    "aws-cdk-lib>=2.232.2,<3.0.0",
    "constructs>=10.0.0,<11.0.0",
]
