network:
  version: 2
  renderer: networkd
  ethernets:
    enp1s0:
      addresses:
        - 192.168.122.10/24

    enp7s0:
      addresses:
        - 172.16.0.10/24
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
      routes:
        - to: default
          via: 172.16.0.1
          metric: 100

    enp8s0:
      addresses:
        - 192.168.100.1/24
      routes:
        - to: 192.168.102.0/24
          via: 192.168.100.30
        - to: 192.168.101.0/24
          via: 192.168.100.20