network:
  version: 2
  renderer: networkd
  ethernets:
    enp1s0:
      addresses:
        - 192.168.122.11/24

    enp7s0:
      addresses:
        - 192.168.100.20/24
      routes:
        - to: 192.168.102.0/24
          via: 192.168.100.1

    enp8s0:
      addresses:
        - 192.168.101.10/24