network:
  version: 2
  renderer: networkd
  ethernets:
    enp1s0:
      addresses:
        - 192.168.122.12/24

    enp7s0:
      addresses:
        - 192.168.100.30/24
      routes:
        - to: default
          via: 192.168.100.1
        - to: 192.168.101.0/24
          via: 192.168.100.1

    enp8s0:
      addresses:
        - 192.168.102.15/24